-- MySQL Script generated by MySQL Workbench
-- Fri Jul 30 05:08:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base` DEFAULT CHARACTER SET utf8 ;
USE `base` ;

-- -----------------------------------------------------
-- Table `base`.`answer_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`answer_text` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `dep_id` INT NOT NULL,
  `to_dep_id` INT NOT NULL,
  `qid` INT NOT NULL,
  `ans` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`answer_vars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`answer_vars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `dep_id` INT NOT NULL,
  `to_dep_id` INT NOT NULL,
  `qid` INT NOT NULL,
  `ans` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`free_deps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`free_deps` (
  `uid` INT NOT NULL,
  `depid` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(255) NULL,
  `admin` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `val` VARCHAR(255) NOT NULL,
  `vars` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `val_UNIQUE` (`val` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `pid` INT NULL,
  `depid` INT NULL,
  `to_pid` INT NULL,
  `step` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `base`.`promo`
-- -----------------------------------------------------
START TRANSACTION;
USE `base`;
INSERT INTO `base`.`promo` (`id`, `name`, `comment`, `admin`) VALUES (1, 'test', 'Тестовый промо', 0x46616C7365);
INSERT INTO `base`.`promo` (`id`, `name`, `comment`, `admin`) VALUES (2, 'C6frq1e-AEYNmfc-7H4x418-N8qvj0n-TKrtG8W', 'admin prmo', 0x54727565);

COMMIT;
